# Imagen base ligera
FROM python:3.12-slim

# Instalar dependencias básicas
RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*

# Directorio de trabajo
WORKDIR /app

# Copiar dependencias desde la raíz del proyecto
COPY requirements.txt .

# Instalar dependencias de Python
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el servidor MCP
COPY app/server/server_mcp.py ./server_mcp.py

# Copiar variables de entorno



# Comando por defecto
CMD ["python", "server_mcp.py"]
